backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  # Main Website Pages
  - name: "pages"
    label: "Website Pages"
    folder: "/"
    create: true
    extension: "html"
    slug: "{{slug}}"
    fields:
      - {label: "Page Title", name: "title", widget: "string", required: true}
      - {label: "Meta Description", name: "description", widget: "text", required: false, hint: "Brief description for search engines"}
      - {label: "Keywords", name: "keywords", widget: "string", required: false, hint: "Comma-separated keywords"}
      - {label: "HTML Content", name: "body", widget: "code", default_language: "html", required: true}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  # News & Announcements
  - name: "news"
    label: "News & Announcements"
    folder: "news"
    create: true
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false, hint: "Brief summary for listings"}
      - {label: "Category", name: "category", widget: "select", options: ["General", "Programming", "Community", "Events", "Awards"], required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: true}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  # Programming Schedule
  - name: "programs"
    label: "TV Programs"
    folder: "programs"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - {label: "Program Name", name: "title", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Genre", name: "genre", widget: "select", options: ["Educational", "News", "Documentary", "Entertainment", "Children", "Sports", "Local", "Public Affairs"], required: false}
      - {label: "Air Time", name: "airtime", widget: "string", required: false, hint: "e.g., Mondays 7:00 PM"}
      - {label: "Duration", name: "duration", widget: "string", required: false, hint: "e.g., 30 minutes"}
      - {label: "Host/Producer", name: "host", widget: "string", required: false}
      - {label: "Program Image", name: "image", widget: "image", required: false}
      - {label: "Website/Links", name: "links", widget: "list", required: false}
      - {label: "Program Details", name: "body", widget: "markdown", required: true}
      - {label: "Active", name: "active", widget: "boolean", default: true}

  # Board Members & Staff
  - name: "people"
    label: "Board & Staff"
    folder: "people"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - {label: "Full Name", name: "title", widget: "string", required: true}
      - {label: "Position/Title", name: "position", widget: "string", required: true}
      - {label: "Role Type", name: "role", widget: "select", options: ["Board Member", "Staff", "Volunteer", "Advisor"], required: true}
      - {label: "Photo", name: "photo", widget: "image", required: false}
      - {label: "Bio", name: "body", widget: "markdown", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Phone", name: "phone", widget: "string", required: false}
      - {label: "Display on Website", name: "public", widget: "boolean", default: true}

  # Stylesheets
  - name: "styles"
    label: "CSS Styles"
    folder: "css"
    create: true
    extension: "css"
    slug: "{{slug}}"
    fields:
      - {label: "Stylesheet Name", name: "title", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "CSS Code", name: "body", widget: "code", default_language: "css", required: true}

# Site Configuration
site_url: https://idaho-broadcasting-foundation.netlify.app
display_url: https://idaho-broadcasting-foundation.netlify.app
logo_url: https://idaho-broadcasting-foundation.netlify.app/images/logo.png

# Editor settings
editor:
  preview: true
